import type { LucideIcon, LucideProps } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  BellDot,
  BellRing,
  BookOpen,
  Bot,
  Box,
  Braces,
  Brain,
  CloudOff,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  Clock,
  Command as CommandIcon,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  FileJson,
  FilePenLine,
  FilePlus,
  Files,
  FileText,
  FlaskConical,
  Flag,
  Folder,
  FolderOpen,
  FolderPlus,
  Gauge,
  Gem,
  GitBranch,
  GitCompare,
  Globe,
  GraduationCap,
  History,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Library,
  LayoutDashboard,
  ListPlus,
  ListTree,
  Loader,
  Lock,
  LogIn,
  LogOut,
  MessagesSquare,
  Minus,
  MoreHorizontal,
  Monitor,
  Moon,
  Network,
  Package,
  Paintbrush,
  Palette,
  Pause,
  Pencil,
  Play,
  Plug,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  ScanSearch,
  ScrollText,
  Search,
  SearchX,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareSlash,
  Star,
  Stethoscope,
  Store,
  Sun,
  Terminal,
  Trash2,
  Upload,
  User,
  WandSparkles,
  Waypoints,
  Webhook,
  Wind,
  Workflow,
  Infinity as InfinityIcon,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * Curated, tree-shakeable icon registry. Icon names come from data (agent
 * definitions, sidebar sections), so we resolve them by string and fall back to
 * a neutral dot when a name is unknown. All icons are outlined (Lucide), per the
 * design interview.
 */
const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'triangle-alert': AlertTriangle,
  archive: Archive,
  'bar-chart-3': BarChart3,
  'bell-dot': BellDot,
  'bell-ring': BellRing,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'book-open': BookOpen,
  bot: Bot,
  box: Box,
  braces: Braces,
  brain: Brain,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  'circle-help': CircleHelp,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  'cloud-off': CloudOff,
  command: CommandIcon,
  copy: Copy,
  cpu: Cpu,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-json': FileJson,
  'file-pen-line': FilePenLine,
  'file-plus': FilePlus,
  'file-text': FileText,
  files: Files,
  flag: Flag,
  'flask-conical': FlaskConical,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  gauge: Gauge,
  gem: Gem,
  'git-branch': GitBranch,
  'git-compare': GitCompare,
  globe: Globe,
  'graduation-cap': GraduationCap,
  history: History,
  info: Info,
  key: KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  library: Library,
  'layout-dashboard': LayoutDashboard,
  'list-plus': ListPlus,
  'list-tree': ListTree,
  loader: Loader,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'messages-square': MessagesSquare,
  minus: Minus,
  'more-horizontal': MoreHorizontal,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  save: Save,
  'scan-search': ScanSearch,
  'scroll-text': ScrollText,
  search: Search,
  'search-x': SearchX,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-x': ShieldX,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  'square-slash': SquareSlash,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  upload: Upload,
  user: User,
  'wand-sparkles': WandSparkles,
  waypoints: Waypoints,
  webhook: Webhook,
  wind: Wind,
  workflow: Workflow,
  infinity: InfinityIcon,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

export interface IconProps extends LucideProps {
  name: string
}

export function Icon({ name, ...props }: IconProps) {
  const Component = REGISTRY[name] ?? Circle
  return <Component {...props} />
}
