import type { LucideIcon, LucideProps } from 'lucide-react'
import {
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bot,
  Box,
  Braces,
  Brain,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  Clock,
  Command as CommandIcon,
  Copy,
  Cpu,
  Download,
  ExternalLink,
  Eye,
  FilePlus,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Gem,
  GitBranch,
  GitCompare,
  Globe,
  GraduationCap,
  History,
  Info,
  KeyRound,
  Keyboard,
  Layers,
  Library,
  LayoutDashboard,
  Loader,
  LogIn,
  LogOut,
  MessagesSquare,
  Monitor,
  Moon,
  Package,
  Paintbrush,
  Palette,
  Pencil,
  Plug,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareSlash,
  Sun,
  Terminal,
  Trash2,
  Upload,
  User,
  Webhook,
  Wrench,
  X,
} from 'lucide-react'

/**
 * Curated, tree-shakeable icon registry. Icon names come from data (agent
 * definitions, sidebar sections), so we resolve them by string and fall back to
 * a neutral dot when a name is unknown. All icons are outlined (Lucide), per the
 * design interview.
 */
const REGISTRY: Record<string, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  bot: Bot,
  box: Box,
  braces: Braces,
  brain: Brain,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  clock: Clock,
  command: CommandIcon,
  copy: Copy,
  cpu: Cpu,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-plus': FilePlus,
  'file-text': FileText,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  gem: Gem,
  'git-branch': GitBranch,
  'git-compare': GitCompare,
  globe: Globe,
  'graduation-cap': GraduationCap,
  history: History,
  info: Info,
  key: KeyRound,
  keyboard: Keyboard,
  layers: Layers,
  library: Library,
  'layout-dashboard': LayoutDashboard,
  loader: Loader,
  'log-in': LogIn,
  'log-out': LogOut,
  'messages-square': MessagesSquare,
  monitor: Monitor,
  moon: Moon,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  pencil: Pencil,
  plug: Plug,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  'square-slash': SquareSlash,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  upload: Upload,
  user: User,
  webhook: Webhook,
  wrench: Wrench,
  x: X,
}

export interface IconProps extends LucideProps {
  name: string
}

export function Icon({ name, ...props }: IconProps) {
  const Component = REGISTRY[name] ?? Circle
  return <Component {...props} />
}
