blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/Fxbixn03/Abyss/discussions
    about: For questions, ideas, or general conversation that does not fit a bug report or feature request.
