import type { ThemeConfig } from '@/shared/types/theme'

/**
 * Global themes (agentId '*') — available to every agent, so the user can pick
 * a neutral color theme independent of the active agent's brand palette.
 */
export const abyssThemes: ThemeConfig[] = [
  {
    id: 'abyss-slate',
    label: 'Abyss — Slate',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#818CF8',
      primaryForeground: '#0B0B12',
      background: '#0B0D12',
      surface: '#14171F',
      border: '#232838',
      text: '#E6E9F2',
      textMuted: '#7A839C',
      sidebar: '#090A0F',
      sidebarActive: '#1B2030',
    },
    light: {
      primary: '#5B63D3',
      primaryForeground: '#FFFFFF',
      background: '#F8F9FC',
      surface: '#FFFFFF',
      border: '#E4E7F0',
      text: '#1A1D29',
      textMuted: '#5A6175',
      sidebar: '#EEF0F8',
      sidebarActive: '#E2E6F4',
    },
  },
  {
    id: 'abyss-mono',
    label: 'Abyss — Mono',
    agentId: '*',
    borderRadius: 'none',
    fontFamily: 'mono',
    dark: {
      primary: '#E0B341',
      primaryForeground: '#1A1505',
      background: '#0B0B0C',
      surface: '#151517',
      border: '#26262A',
      text: '#E6E6E8',
      textMuted: '#7A7A82',
      sidebar: '#08080A',
      sidebarActive: '#1C1C20',
    },
    light: {
      primary: '#B5870B',
      primaryForeground: '#FFFFFF',
      background: '#FAFAFA',
      surface: '#FFFFFF',
      border: '#E4E4E7',
      text: '#18181B',
      textMuted: '#6B6B72',
      sidebar: '#F1F1F2',
      sidebarActive: '#E7E7E9',
    },
  },
  {
    id: 'abyss-warm',
    label: 'Abyss — Warm',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#D97706',
      primaryForeground: '#1C0F00',
      background: '#120D07',
      surface: '#1E1610',
      border: '#352A1A',
      text: '#F2EAD8',
      textMuted: '#9C8A6A',
      sidebar: '#0E0A05',
      sidebarActive: '#2A2015',
    },
    light: {
      primary: '#B45309',
      primaryForeground: '#FFFFFF',
      background: '#FDFAF5',
      surface: '#FFFFFF',
      border: '#EDE0C8',
      text: '#1C1208',
      textMuted: '#78614A',
      sidebar: '#F5EFE3',
      sidebarActive: '#EDE3D1',
    },
  },
  {
    id: 'abyss-contrast',
    label: 'Abyss — High Contrast',
    agentId: '*',
    borderRadius: 'none',
    fontFamily: 'mono',
    dark: {
      primary: '#FACC15',
      primaryForeground: '#0A0A0A',
      background: '#0A0A0A',
      surface: '#141414',
      border: '#3D3D3D',
      text: '#FFFFFF',
      textMuted: '#C8C8C8',
      sidebar: '#050505',
      sidebarActive: '#1F1F1F',
    },
    light: {
      primary: '#0D1B2A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F2F2F2',
      border: '#6B7280',
      text: '#0D1B2A',
      textMuted: '#374151',
      sidebar: '#E8EBF0',
      sidebarActive: '#D1D8E4',
    },
  },
  {
    id: 'abyss-forest',
    label: 'Abyss — Forest',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#34D399',
      primaryForeground: '#021A0E',
      background: '#0A0F0B',
      surface: '#111A13',
      border: '#1E3023',
      text: '#E0F0E8',
      textMuted: '#6B9478',
      sidebar: '#070C08',
      sidebarActive: '#1A2E1E',
    },
    light: {
      primary: '#059669',
      primaryForeground: '#FFFFFF',
      background: '#F5FBF7',
      surface: '#FFFFFF',
      border: '#C6E2CE',
      text: '#0D2016',
      textMuted: '#4A7A5C',
      sidebar: '#E8F5ED',
      sidebarActive: '#D4ECDC',
    },
  },
  {
    id: 'abyss-ocean',
    label: 'Abyss — Ocean',
    agentId: '*',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#38BDF8',
      primaryForeground: '#02111D',
      background: '#060C12',
      surface: '#0D1825',
      border: '#162233',
      text: '#E0EEF8',
      textMuted: '#5A7A96',
      sidebar: '#040810',
      sidebarActive: '#122034',
    },
    light: {
      primary: '#0284C7',
      primaryForeground: '#FFFFFF',
      background: '#F5FAFF',
      surface: '#FFFFFF',
      border: '#BAD8EF',
      text: '#07253D',
      textMuted: '#4A6E87',
      sidebar: '#E0F0FB',
      sidebarActive: '#C9E5F5',
    },
  },
  {
    id: 'abyss-rose',
    label: 'Abyss — Rose',
    agentId: '*',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#FB7185',
      primaryForeground: '#1C0009',
      background: '#120A0D',
      surface: '#1C1014',
      border: '#3A1E26',
      text: '#F2E0E4',
      textMuted: '#9C6E7A',
      sidebar: '#0E0709',
      sidebarActive: '#2E1620',
    },
    light: {
      primary: '#E11D48',
      primaryForeground: '#FFFFFF',
      background: '#FFF5F7',
      surface: '#FFFFFF',
      border: '#F5C0CC',
      text: '#1C0A0F',
      textMuted: '#8A4A5C',
      sidebar: '#FFE8EE',
      sidebarActive: '#FFD6E0',
    },
  },
  {
    id: 'abyss-violet',
    label: 'Abyss — Violet',
    agentId: '*',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#A855F7',
      primaryForeground: '#0D0017',
      background: '#0E0A14',
      surface: '#170F22',
      border: '#2D1F42',
      text: '#EDE8F5',
      textMuted: '#8B7AA8',
      sidebar: '#0A0710',
      sidebarActive: '#251A38',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FAF7FF',
      surface: '#FFFFFF',
      border: '#DDD0F5',
      text: '#1A0F2E',
      textMuted: '#7059A6',
      sidebar: '#F0EAFB',
      sidebarActive: '#E3D6F7',
    },
  },
  {
    id: 'abyss-midnight',
    label: 'Abyss — Midnight',
    agentId: '*',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#7C68EE',
      primaryForeground: '#06050F',
      background: '#070812',
      surface: '#0E1020',
      border: '#1C1E36',
      text: '#E8E9F8',
      textMuted: '#7278A8',
      sidebar: '#05060E',
      sidebarActive: '#191B30',
    },
    light: {
      primary: '#4F3DCB',
      primaryForeground: '#FFFFFF',
      background: '#F7F8FF',
      surface: '#FFFFFF',
      border: '#D8DBF5',
      text: '#0D0E22',
      textMuted: '#5E6290',
      sidebar: '#ECEEFF',
      sidebarActive: '#DDE0F7',
    },
  },
  {
    id: 'abyss-teal',
    label: 'Abyss — Teal',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#0D9488',
      primaryForeground: '#020F0E',
      background: '#060F10',
      surface: '#0D1A1C',
      border: '#163335',
      text: '#DFF2F0',
      textMuted: '#5C8E8A',
      sidebar: '#040C0D',
      sidebarActive: '#122628',
    },
    light: {
      primary: '#0F766E',
      primaryForeground: '#FFFFFF',
      background: '#F2FBFB',
      surface: '#FFFFFF',
      border: '#B2DEDD',
      text: '#082120',
      textMuted: '#3D7572',
      sidebar: '#E2F5F5',
      sidebarActive: '#CCECEA',
    },
  },
  {
    id: 'abyss-crimson',
    label: 'Abyss — Crimson',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#DC2626',
      primaryForeground: '#FFFFFF',
      background: '#120707',
      surface: '#1C0A0A',
      border: '#3B1212',
      text: '#F5E0E0',
      textMuted: '#9C6060',
      sidebar: '#0E0505',
      sidebarActive: '#2D0F0F',
    },
    light: {
      primary: '#B91C1C',
      primaryForeground: '#FFFFFF',
      background: '#FFF8F8',
      surface: '#FFFFFF',
      border: '#F5C6C6',
      text: '#1C0707',
      textMuted: '#8A4A4A',
      sidebar: '#FFE8E8',
      sidebarActive: '#FFD6D6',
    },
  },
  {
    id: 'abyss-copper',
    label: 'Abyss — Copper',
    agentId: '*',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#C2622D',
      primaryForeground: '#0E0300',
      background: '#110A06',
      surface: '#1D1009',
      border: '#3D2216',
      text: '#F2E8E0',
      textMuted: '#9C7560',
      sidebar: '#0C0705',
      sidebarActive: '#2E1A10',
    },
    light: {
      primary: '#A0491E',
      primaryForeground: '#FFFFFF',
      background: '#FDF8F3',
      surface: '#FFFFFF',
      border: '#EDD8C6',
      text: '#1C0D05',
      textMuted: '#8A5A40',
      sidebar: '#F5EBE0',
      sidebarActive: '#EDD9C8',
    },
  },
]
