import type { ThemeConfig } from '@/shared/types/theme'

export const aiderThemes: ThemeConfig[] = [
  {
    id: 'aider-slate',
    label: 'Aider — Slate',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#7FB069',
      primaryForeground: '#0C1408',
      background: '#101311',
      surface: '#1A1F1B',
      border: '#2C342D',
      text: '#E4EAE2',
      textMuted: '#7E8A7C',
      sidebar: '#0B0E0C',
      sidebarActive: '#222B23',
    },
    light: {
      primary: '#4F7942',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F5F7F4',
      border: '#DDE3DA',
      text: '#1A201A',
      textMuted: '#647062',
      sidebar: '#EFF2ED',
      sidebarActive: '#E1E8DD',
    },
  },
  {
    id: 'aider-rust',
    label: 'Aider — Rust',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#B8632A',
      primaryForeground: '#140800',
      background: '#0E0B08',
      surface: '#171210',
      border: '#2A1E18',
      text: '#E8DDD5',
      textMuted: '#7A5E50',
      sidebar: '#090704',
      sidebarActive: '#231812',
    },
    light: {
      primary: '#8B3C10',
      primaryForeground: '#FFFFFF',
      background: '#FDFAF7',
      surface: '#F7F0E8',
      border: '#E0CEC0',
      text: '#1A1008',
      textMuted: '#6A4E3A',
      sidebar: '#F2E8DC',
      sidebarActive: '#E8D8C8',
    },
  },
  {
    id: 'aider-chalk',
    label: 'Aider — Chalk',
    agentId: 'aider',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#D4B896',
      primaryForeground: '#1A0E00',
      background: '#161412',
      surface: '#221E1A',
      border: '#362E28',
      text: '#F0EAE4',
      textMuted: '#8A7868',
      sidebar: '#100E0C',
      sidebarActive: '#2C2420',
    },
    light: {
      primary: '#8B6A44',
      primaryForeground: '#FFFFFF',
      background: '#FDFBF8',
      surface: '#F5F0E8',
      border: '#E0D4C4',
      text: '#1C1610',
      textMuted: '#7A6450',
      sidebar: '#EEE8DC',
      sidebarActive: '#E4D8C8',
    },
  },
]
