import type { ThemeConfig } from '@/shared/types/theme'

export const amazonqThemes: ThemeConfig[] = [
  {
    id: 'amazonq-dark',
    label: 'Amazon Q — Dark',
    agentId: 'amazonq',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#FF9900',
      primaryForeground: '#1A0800',
      background: '#0A0C10',
      surface: '#141820',
      border: '#252A3A',
      text: '#EAEBf0',
      textMuted: '#6A7090',
      sidebar: '#070910',
      sidebarActive: '#1E2338',
    },
    light: {
      primary: '#CC7700',
      primaryForeground: '#FFFFFF',
      background: '#FAFBFF',
      surface: '#F0F2FC',
      border: '#D8DCF0',
      text: '#0A0D1A',
      textMuted: '#5A6080',
      sidebar: '#EAECF8',
      sidebarActive: '#D8DCF0',
    },
  },
  {
    id: 'amazonq-light',
    label: 'Amazon Q — Light',
    agentId: 'amazonq',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E8850A',
      primaryForeground: '#1A0800',
      background: '#0E0C0A',
      surface: '#181510',
      border: '#2A2418',
      text: '#F0EAE0',
      textMuted: '#8A7A60',
      sidebar: '#0A0806',
      sidebarActive: '#251E14',
    },
    light: {
      primary: '#8B6914',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FAF8F4',
      border: '#E8E0D0',
      text: '#1A160A',
      textMuted: '#6A6050',
      sidebar: '#F5F0E8',
      sidebarActive: '#EDE4D4',
    },
  },
]
