import type { ThemeConfig } from '@/shared/types/theme'

export const ampThemes: ThemeConfig[] = [
  {
    id: 'amp-forge',
    label: 'Amp — Forge',
    agentId: 'amp',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#F59E0B',
      primaryForeground: '#1C1200',
      background: '#141210',
      surface: '#1E1B16',
      border: '#332D20',
      text: '#F0EAD6',
      textMuted: '#8A7E60',
      sidebar: '#0D0B08',
      sidebarActive: '#2B2416',
    },
    light: {
      primary: '#B45309',
      primaryForeground: '#FFFFFF',
      background: '#FFFBF0',
      surface: '#FFF7E1',
      border: '#F0DFA0',
      text: '#1C1200',
      textMuted: '#7A6830',
      sidebar: '#FFF3CC',
      sidebarActive: '#FDEEA0',
    },
  },
  {
    id: 'amp-ember',
    label: 'Amp — Ember',
    agentId: 'amp',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#D94F1E',
      primaryForeground: '#1A0600',
      background: '#100C08',
      surface: '#1C120D',
      border: '#301A12',
      text: '#F0E0D8',
      textMuted: '#8A5040',
      sidebar: '#0B0806',
      sidebarActive: '#271510',
    },
    light: {
      primary: '#D94F1E',
      primaryForeground: '#FFFFFF',
      background: '#FDF8F4',
      surface: '#FBF0E8',
      border: '#F0D8C8',
      text: '#1A0800',
      textMuted: '#7A4030',
      sidebar: '#F5E8DC',
      sidebarActive: '#EED8C8',
    },
  },
]
