import type { ThemeConfig } from '@/shared/types/theme'

export const claudeThemes: ThemeConfig[] = [
  {
    id: 'claude-dusk',
    label: 'Claude — Dusk',
    agentId: 'claude',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#D4956A',
      primaryForeground: '#1A1410',
      background: '#0F0D0B',
      surface: '#1A1715',
      border: '#2E2926',
      text: '#E8E0D8',
      textMuted: '#8A7E74',
      sidebar: '#12100E',
      sidebarActive: '#2A2320',
    },
    light: {
      primary: '#B5703B',
      primaryForeground: '#FFFFFF',
      background: '#FAF7F2',
      surface: '#FFFFFF',
      border: '#E7DFD4',
      text: '#2A2018',
      textMuted: '#8A7E74',
      sidebar: '#F3ECE2',
      sidebarActive: '#E9DFD1',
    },
  },
  {
    id: 'claude-monochrome',
    label: 'Claude — Monochrome',
    agentId: 'claude',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#A0A0A0',
      primaryForeground: '#0A0A0A',
      background: '#121212',
      surface: '#1C1C1C',
      border: '#2E2E2E',
      text: '#E0E0E0',
      textMuted: '#7A7A7A',
      sidebar: '#0E0E0E',
      sidebarActive: '#262626',
    },
    light: {
      primary: '#5A5A5A',
      primaryForeground: '#FFFFFF',
      background: '#F5F5F5',
      surface: '#FFFFFF',
      border: '#DCDCDC',
      text: '#1F1F1F',
      textMuted: '#707070',
      sidebar: '#EAEAEA',
      sidebarActive: '#DEDEDE',
    },
  },
  {
    id: 'claude-black-white',
    label: 'Claude — Black & White',
    agentId: 'claude',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#FFFFFF',
      primaryForeground: '#000000',
      background: '#000000',
      surface: '#0A0A0A',
      border: '#333333',
      text: '#FFFFFF',
      textMuted: '#999999',
      sidebar: '#000000',
      sidebarActive: '#1A1A1A',
    },
    light: {
      primary: '#000000',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      border: '#1A1A1A',
      text: '#000000',
      textMuted: '#666666',
      sidebar: '#F2F2F2',
      sidebarActive: '#E5E5E5',
    },
  },
]
