import type { ThemeConfig } from '@/shared/types/theme'

export const clineThemes: ThemeConfig[] = [
  {
    id: 'cline-night',
    label: 'Cline — Night',
    agentId: 'cline',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#1A0F2E',
      background: '#0E0D14',
      surface: '#17151F',
      border: '#2A2738',
      text: '#E8E6F0',
      textMuted: '#827E96',
      sidebar: '#09080F',
      sidebarActive: '#211D33',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F8F7FC',
      border: '#E5E1F0',
      text: '#1B1826',
      textMuted: '#6B6680',
      sidebar: '#F1EFF9',
      sidebarActive: '#E6E0F5',
    },
  },
  {
    id: 'cline-dawn',
    label: 'Cline — Dawn',
    agentId: 'cline',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#E879A8',
      primaryForeground: '#200010',
      background: '#110A14',
      surface: '#1A1020',
      border: '#2E1A38',
      text: '#F0E0F5',
      textMuted: '#8A5A90',
      sidebar: '#0C0610',
      sidebarActive: '#25122E',
    },
    light: {
      primary: '#C42A70',
      primaryForeground: '#FFFFFF',
      background: '#FFF8FC',
      surface: '#FDEEF6',
      border: '#F0CEDF',
      text: '#200010',
      textMuted: '#7A3060',
      sidebar: '#FAE4F0',
      sidebarActive: '#F5D0E5',
    },
  },
]
