import type { ThemeConfig } from '@/shared/types/theme'

export const codexThemes: ThemeConfig[] = [
  {
    id: 'codex-terminal',
    label: 'Codex — Terminal',
    agentId: 'codex',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#10A37F',
      primaryForeground: '#FFFFFF',
      background: '#0D0D0D',
      surface: '#171717',
      border: '#2D2D2D',
      text: '#ECECEC',
      textMuted: '#6B6B6B',
      sidebar: '#0A0A0A',
      sidebarActive: '#1F1F1F',
    },
    light: {
      primary: '#0E8C6D',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      border: '#E2E2E2',
      text: '#1A1A1A',
      textMuted: '#6B6B6B',
      sidebar: '#F0F0F0',
      sidebarActive: '#E6E6E6',
    },
  },
  {
    id: 'codex-monochrome',
    label: 'Codex — Monochrome',
    agentId: 'codex',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#A0A0A0',
      primaryForeground: '#0A0A0A',
      background: '#121212',
      surface: '#1C1C1C',
      border: '#2E2E2E',
      text: '#E0E0E0',
      textMuted: '#7A7A7A',
      sidebar: '#0E0E0E',
      sidebarActive: '#262626',
    },
    light: {
      primary: '#5A5A5A',
      primaryForeground: '#FFFFFF',
      background: '#F5F5F5',
      surface: '#FFFFFF',
      border: '#DCDCDC',
      text: '#1F1F1F',
      textMuted: '#707070',
      sidebar: '#EAEAEA',
      sidebarActive: '#DEDEDE',
    },
  },
  {
    id: 'codex-black-white',
    label: 'Codex — Black & White',
    agentId: 'codex',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#FFFFFF',
      primaryForeground: '#000000',
      background: '#000000',
      surface: '#0A0A0A',
      border: '#333333',
      text: '#FFFFFF',
      textMuted: '#999999',
      sidebar: '#000000',
      sidebarActive: '#1A1A1A',
    },
    light: {
      primary: '#000000',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      border: '#1A1A1A',
      text: '#000000',
      textMuted: '#666666',
      sidebar: '#F2F2F2',
      sidebarActive: '#E5E5E5',
    },
  },
]
