import type { ThemeConfig } from '@/shared/types/theme'

export const codyThemes: ThemeConfig[] = [
  {
    id: 'cody-nebula',
    label: 'Cody — Nebula',
    agentId: 'cody',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#CC44FF',
      primaryForeground: '#1A0028',
      background: '#0C0814',
      surface: '#160E22',
      border: '#2E1850',
      text: '#EDD8FF',
      textMuted: '#7A4AA0',
      sidebar: '#080510',
      sidebarActive: '#1E1030',
    },
    light: {
      primary: '#9900CC',
      primaryForeground: '#FFFFFF',
      background: '#FBF5FF',
      surface: '#F3E8FF',
      border: '#D8AAEE',
      text: '#1A0830',
      textMuted: '#7A3A99',
      sidebar: '#EDD8FF',
      sidebarActive: '#E0C0F8',
    },
  },
  {
    id: 'cody-magenta',
    label: 'Cody — Magenta',
    agentId: 'cody',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#FF2D9C',
      primaryForeground: '#280010',
      background: '#100810',
      surface: '#1A0E1C',
      border: '#3A1040',
      text: '#FFD8F0',
      textMuted: '#8A3068',
      sidebar: '#0C060E',
      sidebarActive: '#260C28',
    },
    light: {
      primary: '#CC0073',
      primaryForeground: '#FFFFFF',
      background: '#FFF5FA',
      surface: '#FFE8F4',
      border: '#EEBBD8',
      text: '#280018',
      textMuted: '#882050',
      sidebar: '#FFD8EE',
      sidebarActive: '#FFC0E4',
    },
  },
]
