import type { ThemeConfig } from '@/shared/types/theme'

export const continueThemes: ThemeConfig[] = [
  {
    id: 'continue-loop',
    label: 'Continue — Loop',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E6E6E6',
      primaryForeground: '#121212',
      background: '#0D0D0D',
      surface: '#181818',
      border: '#2C2C2C',
      text: '#EDEDED',
      textMuted: '#8A8A8A',
      sidebar: '#070707',
      sidebarActive: '#222222',
    },
    light: {
      primary: '#1A1A1A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      border: '#E2E2E2',
      text: '#1A1A1A',
      textMuted: '#6A6A6A',
      sidebar: '#F2F2F2',
      sidebarActive: '#E6E6E6',
    },
  },
  {
    id: 'continue-ember',
    label: 'Continue — Ember',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E8622A',
      primaryForeground: '#1A0800',
      background: '#0F0A08',
      surface: '#1A110D',
      border: '#2E1C14',
      text: '#F0E0D8',
      textMuted: '#8A5C48',
      sidebar: '#0A0604',
      sidebarActive: '#271510',
    },
    light: {
      primary: '#C0440E',
      primaryForeground: '#FFFFFF',
      background: '#FFFAF7',
      surface: '#FFF3EC',
      border: '#F0D4C4',
      text: '#1A0800',
      textMuted: '#7A4030',
      sidebar: '#FEEEE4',
      sidebarActive: '#FDE0CC',
    },
  },
  {
    id: 'continue-tide',
    label: 'Continue — Tide',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#080E12',
      background: '#080E12',
      surface: '#0D1820',
      border: '#1A2D3A',
      text: '#D4EBF2',
      textMuted: '#4D7A8A',
      sidebar: '#050C10',
      sidebarActive: '#112230',
    },
    light: {
      primary: '#0D9488',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0F7F8',
      border: '#C8DDE0',
      text: '#0D2B30',
      textMuted: '#4A7A82',
      sidebar: '#E6F2F4',
      sidebarActive: '#D0E8EC',
    },
  },
]
