import type { ThemeConfig } from '@/shared/types/theme'

export const copilotThemes: ThemeConfig[] = [
  {
    id: 'copilot-mono',
    label: 'Copilot — Mono',
    agentId: 'copilot',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#6E7681',
      primaryForeground: '#FFFFFF',
      background: '#0D1117',
      surface: '#161B22',
      border: '#30363D',
      text: '#E6EDF3',
      textMuted: '#7D8590',
      sidebar: '#010409',
      sidebarActive: '#21262D',
    },
    light: {
      primary: '#57606A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F6F8FA',
      border: '#D0D7DE',
      text: '#1F2328',
      textMuted: '#656D76',
      sidebar: '#F6F8FA',
      sidebarActive: '#EAEEF2',
    },
  },
  {
    id: 'copilot-spark',
    label: 'Copilot — Spark',
    agentId: 'copilot',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#2F81F7',
      primaryForeground: '#FFFFFF',
      background: '#0D1117',
      surface: '#161B22',
      border: '#30363D',
      text: '#E6EDF3',
      textMuted: '#7D8590',
      sidebar: '#010409',
      sidebarActive: '#1C2B45',
    },
    light: {
      primary: '#0969DA',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F6F8FA',
      border: '#D0D7DE',
      text: '#1F2328',
      textMuted: '#656D76',
      sidebar: '#F6F8FA',
      sidebarActive: '#DDF4FF',
    },
  },
  {
    id: 'copilot-phantom',
    label: 'Copilot — Phantom',
    agentId: 'copilot',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#9D4EDD',
      primaryForeground: '#FFFFFF',
      background: '#0D0A14',
      surface: '#160F22',
      border: '#2D1F42',
      text: '#E8E0F0',
      textMuted: '#8B7AA8',
      sidebar: '#080510',
      sidebarActive: '#251540',
    },
    light: {
      primary: '#7B2FBE',
      primaryForeground: '#FFFFFF',
      background: '#F8F5FF',
      surface: '#F0EAFA',
      border: '#D6C8EF',
      text: '#1E1428',
      textMuted: '#6B5A85',
      sidebar: '#EDE5FA',
      sidebarActive: '#DDD0F5',
    },
  },
]
