import type { ThemeConfig } from '@/shared/types/theme'

export const cursorThemes: ThemeConfig[] = [
  {
    id: 'cursor-graphite',
    label: 'Cursor — Graphite',
    agentId: 'cursor',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#6C8EEF',
      primaryForeground: '#FFFFFF',
      background: '#0E0F12',
      surface: '#17191F',
      border: '#2A2D36',
      text: '#E6E8EE',
      textMuted: '#7A7F8C',
      sidebar: '#0A0B0E',
      sidebarActive: '#20242E',
    },
    light: {
      primary: '#3B5BDB',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F6F7F9',
      border: '#E1E4EA',
      text: '#1A1C22',
      textMuted: '#6B7280',
      sidebar: '#EEF0F3',
      sidebarActive: '#E2E6EC',
    },
  },
  {
    id: 'cursor-aurora',
    label: 'Cursor — Aurora',
    agentId: 'cursor',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#8B5CF6',
      primaryForeground: '#FFFFFF',
      background: '#0C0A14',
      surface: '#16121F',
      border: '#2C2440',
      text: '#ECE8F5',
      textMuted: '#857B9C',
      sidebar: '#0A0810',
      sidebarActive: '#221A33',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F8F6FC',
      border: '#E7E1F2',
      text: '#1E1A29',
      textMuted: '#6E6880',
      sidebar: '#F1ECF9',
      sidebarActive: '#E6DEF5',
    },
  },
  {
    id: 'cursor-frost',
    label: 'Cursor — Frost',
    agentId: 'cursor',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#A5F3FC',
      primaryForeground: '#0C1A2E',
      background: '#050D1A',
      surface: '#0C1A2E',
      border: '#1A3050',
      text: '#E0F2FE',
      textMuted: '#5E8BA8',
      sidebar: '#030A12',
      sidebarActive: '#112240',
    },
    light: {
      primary: '#0891B2',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0F9FF',
      border: '#BAE6FD',
      text: '#0C1A2E',
      textMuted: '#4B7A94',
      sidebar: '#E0F2FE',
      sidebarActive: '#BAE6FD',
    },
  },
]
