import type { ThemeConfig } from '@/shared/types/theme'

export const devinThemes: ThemeConfig[] = [
  {
    id: 'devin-carbon',
    label: 'Devin — Carbon',
    agentId: 'devin',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#3B82F6',
      primaryForeground: '#000D2A',
      background: '#0A0C0F',
      surface: '#111418',
      border: '#1E2530',
      text: '#D4DDE8',
      textMuted: '#4A5A70',
      sidebar: '#060809',
      sidebarActive: '#161C26',
    },
    light: {
      primary: '#1D4ED8',
      primaryForeground: '#FFFFFF',
      background: '#F5F7FA',
      surface: '#E8EDF5',
      border: '#C0CCE0',
      text: '#0A1020',
      textMuted: '#3A4A64',
      sidebar: '#DDE4F0',
      sidebarActive: '#C8D4E8',
    },
  },
  {
    id: 'devin-electric',
    label: 'Devin — Electric',
    agentId: 'devin',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#60CFFF',
      primaryForeground: '#001828',
      background: '#080E14',
      surface: '#0E1820',
      border: '#182838',
      text: '#C8E8F8',
      textMuted: '#3A6080',
      sidebar: '#050A0F',
      sidebarActive: '#102030',
    },
    light: {
      primary: '#005A9E',
      primaryForeground: '#FFFFFF',
      background: '#F0F8FF',
      surface: '#E0F0FC',
      border: '#A8CFF0',
      text: '#001830',
      textMuted: '#2A5880',
      sidebar: '#D0E8F8',
      sidebarActive: '#B8DCFC',
    },
  },
]
