import type { ThemeConfig } from '@/shared/types/theme'

export const geminiThemes: ThemeConfig[] = [
  {
    id: 'gemini-cosmos',
    label: 'Gemini — Cosmos',
    agentId: 'gemini',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#4285F4',
      primaryForeground: '#FFFFFF',
      background: '#0C0E14',
      surface: '#141720',
      border: '#22263A',
      text: '#E3E8F4',
      textMuted: '#6B7494',
      sidebar: '#090B10',
      sidebarActive: '#1C2035',
    },
    light: {
      primary: '#2D6FE0',
      primaryForeground: '#FFFFFF',
      background: '#FAFBFF',
      surface: '#FFFFFF',
      border: '#DDE3F0',
      text: '#1A2030',
      textMuted: '#5B6480',
      sidebar: '#EEF2FC',
      sidebarActive: '#E1E8F8',
    },
  },
  {
    id: 'gemini-aurora',
    label: 'Gemini — Aurora',
    agentId: 'gemini',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#7C6BFF',
      primaryForeground: '#FFFFFF',
      background: '#0A0B14',
      surface: '#12132A',
      border: '#1E2040',
      text: '#DDD9FF',
      textMuted: '#6B6A9A',
      sidebar: '#07080F',
      sidebarActive: '#181930',
    },
    light: {
      primary: '#7C6BFF',
      primaryForeground: '#FFFFFF',
      background: '#F8F7FF',
      surface: '#FFFFFF',
      border: '#D8D4F5',
      text: '#1A1840',
      textMuted: '#6B6A9A',
      sidebar: '#EEEBff',
      sidebarActive: '#E0DCFF',
    },
  },
  {
    id: 'gemini-solar',
    label: 'Gemini — Solar',
    agentId: 'gemini',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#F9AB00',
      primaryForeground: '#0F0C00',
      background: '#0F0C00',
      surface: '#1A1600',
      border: '#2E2500',
      text: '#F5E6B0',
      textMuted: '#8C7A3A',
      sidebar: '#0B0900',
      sidebarActive: '#241E00',
    },
    light: {
      primary: '#E37400',
      primaryForeground: '#FFFFFF',
      background: '#FFFDF5',
      surface: '#FFFFFF',
      border: '#F0E4C0',
      text: '#2B1D00',
      textMuted: '#8C6A2A',
      sidebar: '#FFF8E1',
      sidebarActive: '#FFE9A0',
    },
  },
]
