import type { ThemeConfig } from '@/shared/types/theme'

export const gooseThemes: ThemeConfig[] = [
  {
    id: 'goose-feather',
    label: 'Goose — Feather',
    agentId: 'goose',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#021A18',
      background: '#080F0F',
      surface: '#0F1A1A',
      border: '#1A2E2D',
      text: '#E2F5F4',
      textMuted: '#5E8C89',
      sidebar: '#050C0C',
      sidebarActive: '#132322',
    },
    light: {
      primary: '#0D9488',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0FAFA',
      border: '#CCEAE8',
      text: '#0A1F1E',
      textMuted: '#4A7A77',
      sidebar: '#E8F7F6',
      sidebarActive: '#D1EFED',
    },
  },
  {
    id: 'goose-moss',
    label: 'Goose — Moss',
    agentId: 'goose',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#6B8F5E',
      primaryForeground: '#050F04',
      background: '#0A0F09',
      surface: '#121A11',
      border: '#1E2E1C',
      text: '#E0EAD8',
      textMuted: '#5A7050',
      sidebar: '#060C05',
      sidebarActive: '#182416',
    },
    light: {
      primary: '#6B8F5E',
      primaryForeground: '#FFFFFF',
      background: '#F9FAF7',
      surface: '#F1F5EE',
      border: '#D8E4D2',
      text: '#0F1A0E',
      textMuted: '#5A7050',
      sidebar: '#EAF0E6',
      sidebarActive: '#DCE8D6',
    },
  },
]
