import type { ThemeConfig } from '@/shared/types/theme'

export const kiroThemes: ThemeConfig[] = [
  {
    id: 'kiro-nimbus',
    label: 'Kiro — Nimbus',
    agentId: 'kiro',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#FF9900',
      primaryForeground: '#1A0A00',
      background: '#0A0D14',
      surface: '#131720',
      border: '#232840',
      text: '#E8EAF4',
      textMuted: '#6A7090',
      sidebar: '#070A10',
      sidebarActive: '#1C2238',
    },
    light: {
      primary: '#FF9900',
      primaryForeground: '#FFFFFF',
      background: '#FAFBFF',
      surface: '#F0F2FC',
      border: '#D8DCF0',
      text: '#0A0D1A',
      textMuted: '#5A6080',
      sidebar: '#EAECF8',
      sidebarActive: '#D8DCF0',
    },
  },
  {
    id: 'kiro-storm',
    label: 'Kiro — Storm',
    agentId: 'kiro',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#FF6600',
      primaryForeground: '#1A0500',
      background: '#0D0C0A',
      surface: '#181614',
      border: '#2E2820',
      text: '#F0EAE0',
      textMuted: '#8A7A60',
      sidebar: '#090806',
      sidebarActive: '#281F14',
    },
    light: {
      primary: '#CC5200',
      primaryForeground: '#FFFFFF',
      background: '#FFFCF8',
      surface: '#FFF5EA',
      border: '#F0DDCC',
      text: '#1A0E06',
      textMuted: '#7A5A3A',
      sidebar: '#FDEEDD',
      sidebarActive: '#FAE0C4',
    },
  },
  {
    id: 'kiro-cirrus',
    label: 'Kiro — Cirrus',
    agentId: 'kiro',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#00A8E1',
      primaryForeground: '#001A26',
      background: '#080E14',
      surface: '#0D1924',
      border: '#162840',
      text: '#D6EAF8',
      textMuted: '#5A7A94',
      sidebar: '#050A0F',
      sidebarActive: '#112234',
    },
    light: {
      primary: '#0078C8',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0F5FA',
      border: '#C8D8E8',
      text: '#0A1620',
      textMuted: '#4A6478',
      sidebar: '#E4EEF6',
      sidebarActive: '#D0E2F0',
    },
  },
]
