import type { ThemeConfig } from '@/shared/types/theme'

/** Presets for the additional adapter-registry agents (one default theme each). */
export const moreAgentThemes: ThemeConfig[] = [
  {
    id: 'windsurf-wave',
    label: 'Windsurf — Wave',
    agentId: 'windsurf',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#13C2C2',
      primaryForeground: '#04201F',
      background: '#0A1414',
      surface: '#10201F',
      border: '#1F3A38',
      text: '#E2F2F1',
      textMuted: '#6E908D',
      sidebar: '#06100F',
      sidebarActive: '#143230',
    },
    light: {
      primary: '#0E8F8F',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F2FAFA',
      border: '#D2E8E7',
      text: '#0E2422',
      textMuted: '#5C7D7A',
      sidebar: '#ECF7F6',
      sidebarActive: '#D9F0EF',
    },
  },
  {
    id: 'continue-loop',
    label: 'Continue — Loop',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E6E6E6',
      primaryForeground: '#121212',
      background: '#0D0D0D',
      surface: '#181818',
      border: '#2C2C2C',
      text: '#EDEDED',
      textMuted: '#8A8A8A',
      sidebar: '#070707',
      sidebarActive: '#222222',
    },
    light: {
      primary: '#1A1A1A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      border: '#E2E2E2',
      text: '#1A1A1A',
      textMuted: '#6A6A6A',
      sidebar: '#F2F2F2',
      sidebarActive: '#E6E6E6',
    },
  },
  {
    id: 'aider-slate',
    label: 'Aider — Slate',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#7FB069',
      primaryForeground: '#0C1408',
      background: '#101311',
      surface: '#1A1F1B',
      border: '#2C342D',
      text: '#E4EAE2',
      textMuted: '#7E8A7C',
      sidebar: '#0B0E0C',
      sidebarActive: '#222B23',
    },
    light: {
      primary: '#4F7942',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F5F7F4',
      border: '#DDE3DA',
      text: '#1A201A',
      textMuted: '#647062',
      sidebar: '#EFF2ED',
      sidebarActive: '#E1E8DD',
    },
  },
  {
    id: 'cline-night',
    label: 'Cline — Night',
    agentId: 'cline',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#1A0F2E',
      background: '#0E0D14',
      surface: '#17151F',
      border: '#2A2738',
      text: '#E8E6F0',
      textMuted: '#827E96',
      sidebar: '#09080F',
      sidebarActive: '#211D33',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F8F7FC',
      border: '#E5E1F0',
      text: '#1B1826',
      textMuted: '#6B6680',
      sidebar: '#F1EFF9',
      sidebarActive: '#E6E0F5',
    },
  },
]
