import type { ThemeConfig } from '@/shared/types/theme'

/** Presets for the additional adapter-registry agents (one default theme each). */
export const moreAgentThemes: ThemeConfig[] = [
  {
    id: 'windsurf-wave',
    label: 'Windsurf — Wave',
    agentId: 'windsurf',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#13C2C2',
      primaryForeground: '#04201F',
      background: '#0A1414',
      surface: '#10201F',
      border: '#1F3A38',
      text: '#E2F2F1',
      textMuted: '#6E908D',
      sidebar: '#06100F',
      sidebarActive: '#143230',
    },
    light: {
      primary: '#0E8F8F',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F2FAFA',
      border: '#D2E8E7',
      text: '#0E2422',
      textMuted: '#5C7D7A',
      sidebar: '#ECF7F6',
      sidebarActive: '#D9F0EF',
    },
  },
  {
    id: 'windsurf-storm',
    label: 'Windsurf — Storm',
    agentId: 'windsurf',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#00F5FF',
      primaryForeground: '#001820',
      background: '#040D12',
      surface: '#091520',
      border: '#0E2A3A',
      text: '#C8F0FF',
      textMuted: '#3D7A8A',
      sidebar: '#020A0F',
      sidebarActive: '#0A2030',
    },
    light: {
      primary: '#006F80',
      primaryForeground: '#FFFFFF',
      background: '#F0FAFF',
      surface: '#E2F5FC',
      border: '#B0DCE8',
      text: '#062030',
      textMuted: '#3A6878',
      sidebar: '#D8EFF8',
      sidebarActive: '#C0E4F2',
    },
  },
  {
    id: 'continue-loop',
    label: 'Continue — Loop',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E6E6E6',
      primaryForeground: '#121212',
      background: '#0D0D0D',
      surface: '#181818',
      border: '#2C2C2C',
      text: '#EDEDED',
      textMuted: '#8A8A8A',
      sidebar: '#070707',
      sidebarActive: '#222222',
    },
    light: {
      primary: '#1A1A1A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      border: '#E2E2E2',
      text: '#1A1A1A',
      textMuted: '#6A6A6A',
      sidebar: '#F2F2F2',
      sidebarActive: '#E6E6E6',
    },
  },
  {
    id: 'continue-ember',
    label: 'Continue — Ember',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E8622A',
      primaryForeground: '#1A0800',
      background: '#0F0A08',
      surface: '#1A110D',
      border: '#2E1C14',
      text: '#F0E0D8',
      textMuted: '#8A5C48',
      sidebar: '#0A0604',
      sidebarActive: '#271510',
    },
    light: {
      primary: '#C0440E',
      primaryForeground: '#FFFFFF',
      background: '#FFFAF7',
      surface: '#FFF3EC',
      border: '#F0D4C4',
      text: '#1A0800',
      textMuted: '#7A4030',
      sidebar: '#FEEEE4',
      sidebarActive: '#FDE0CC',
    },
  },
  {
    id: 'aider-slate',
    label: 'Aider — Slate',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#7FB069',
      primaryForeground: '#0C1408',
      background: '#101311',
      surface: '#1A1F1B',
      border: '#2C342D',
      text: '#E4EAE2',
      textMuted: '#7E8A7C',
      sidebar: '#0B0E0C',
      sidebarActive: '#222B23',
    },
    light: {
      primary: '#4F7942',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F5F7F4',
      border: '#DDE3DA',
      text: '#1A201A',
      textMuted: '#647062',
      sidebar: '#EFF2ED',
      sidebarActive: '#E1E8DD',
    },
  },
  {
    id: 'aider-rust',
    label: 'Aider — Rust',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#B8632A',
      primaryForeground: '#140800',
      background: '#0E0B08',
      surface: '#171210',
      border: '#2A1E18',
      text: '#E8DDD5',
      textMuted: '#7A5E50',
      sidebar: '#090704',
      sidebarActive: '#231812',
    },
    light: {
      primary: '#8B3C10',
      primaryForeground: '#FFFFFF',
      background: '#FDFAF7',
      surface: '#F7F0E8',
      border: '#E0CEC0',
      text: '#1A1008',
      textMuted: '#6A4E3A',
      sidebar: '#F2E8DC',
      sidebarActive: '#E8D8C8',
    },
  },
  {
    id: 'cline-night',
    label: 'Cline — Night',
    agentId: 'cline',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#1A0F2E',
      background: '#0E0D14',
      surface: '#17151F',
      border: '#2A2738',
      text: '#E8E6F0',
      textMuted: '#827E96',
      sidebar: '#09080F',
      sidebarActive: '#211D33',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F8F7FC',
      border: '#E5E1F0',
      text: '#1B1826',
      textMuted: '#6B6680',
      sidebar: '#F1EFF9',
      sidebarActive: '#E6E0F5',
    },
  },
  {
    id: 'cline-dawn',
    label: 'Cline — Dawn',
    agentId: 'cline',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#E879A8',
      primaryForeground: '#200010',
      background: '#110A14',
      surface: '#1A1020',
      border: '#2E1A38',
      text: '#F0E0F5',
      textMuted: '#8A5A90',
      sidebar: '#0C0610',
      sidebarActive: '#25122E',
    },
    light: {
      primary: '#C42A70',
      primaryForeground: '#FFFFFF',
      background: '#FFF8FC',
      surface: '#FDEEF6',
      border: '#F0CEDF',
      text: '#200010',
      textMuted: '#7A3060',
      sidebar: '#FAE4F0',
      sidebarActive: '#F5D0E5',
    },
  },
  {
    id: 'roo-circuit',
    label: 'Roo Code — Circuit',
    agentId: 'roo',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#22D3A0',
      primaryForeground: '#011A12',
      background: '#080F0D',
      surface: '#0F1A17',
      border: '#1A302A',
      text: '#DAFAF0',
      textMuted: '#4D8C75',
      sidebar: '#050C09',
      sidebarActive: '#122620',
    },
    light: {
      primary: '#0B9E72',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0FBF6',
      border: '#C2EAD9',
      text: '#0A1F18',
      textMuted: '#3D7A62',
      sidebar: '#E4F7EE',
      sidebarActive: '#C8F0DE',
    },
  },
  {
    id: 'roo-pulse',
    label: 'Roo Code — Pulse',
    agentId: 'roo',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#C4A832',
      primaryForeground: '#120E00',
      background: '#0D0F08',
      surface: '#171A0E',
      border: '#2C2E18',
      text: '#F0EDD8',
      textMuted: '#7A7440',
      sidebar: '#090B06',
      sidebarActive: '#222510',
    },
    light: {
      primary: '#8A7010',
      primaryForeground: '#FFFFFF',
      background: '#FDFCF4',
      surface: '#F8F4E2',
      border: '#E0D8A8',
      text: '#1A1800',
      textMuted: '#6A6030',
      sidebar: '#F2EDD4',
      sidebarActive: '#EAE4BC',
    },
  },
  {
    id: 'amp-forge',
    label: 'Amp — Forge',
    agentId: 'amp',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#F59E0B',
      primaryForeground: '#1C1200',
      background: '#141210',
      surface: '#1E1B16',
      border: '#332D20',
      text: '#F0EAD6',
      textMuted: '#8A7E60',
      sidebar: '#0D0B08',
      sidebarActive: '#2B2416',
    },
    light: {
      primary: '#B45309',
      primaryForeground: '#FFFFFF',
      background: '#FFFBF0',
      surface: '#FFF7E1',
      border: '#F0DFA0',
      text: '#1C1200',
      textMuted: '#7A6830',
      sidebar: '#FFF3CC',
      sidebarActive: '#FDEEA0',
    },
  },
  {
    id: 'amp-ember',
    label: 'Amp — Ember',
    agentId: 'amp',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#D94F1E',
      primaryForeground: '#1A0600',
      background: '#100C08',
      surface: '#1C120D',
      border: '#301A12',
      text: '#F0E0D8',
      textMuted: '#8A5040',
      sidebar: '#0B0806',
      sidebarActive: '#271510',
    },
    light: {
      primary: '#D94F1E',
      primaryForeground: '#FFFFFF',
      background: '#FDF8F4',
      surface: '#FBF0E8',
      border: '#F0D8C8',
      text: '#1A0800',
      textMuted: '#7A4030',
      sidebar: '#F5E8DC',
      sidebarActive: '#EED8C8',
    },
  },
  {
    id: 'goose-feather',
    label: 'Goose — Feather',
    agentId: 'goose',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#021A18',
      background: '#080F0F',
      surface: '#0F1A1A',
      border: '#1A2E2D',
      text: '#E2F5F4',
      textMuted: '#5E8C89',
      sidebar: '#050C0C',
      sidebarActive: '#132322',
    },
    light: {
      primary: '#0D9488',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0FAFA',
      border: '#CCEAE8',
      text: '#0A1F1E',
      textMuted: '#4A7A77',
      sidebar: '#E8F7F6',
      sidebarActive: '#D1EFED',
    },
  },
  {
    id: 'goose-moss',
    label: 'Goose — Moss',
    agentId: 'goose',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#6B8F5E',
      primaryForeground: '#050F04',
      background: '#0A0F09',
      surface: '#121A11',
      border: '#1E2E1C',
      text: '#E0EAD8',
      textMuted: '#5A7050',
      sidebar: '#060C05',
      sidebarActive: '#182416',
    },
    light: {
      primary: '#6B8F5E',
      primaryForeground: '#FFFFFF',
      background: '#F9FAF7',
      surface: '#F1F5EE',
      border: '#D8E4D2',
      text: '#0F1A0E',
      textMuted: '#5A7050',
      sidebar: '#EAF0E6',
      sidebarActive: '#DCE8D6',
    },
  },
  {
    id: 'kiro-nimbus',
    label: 'Kiro — Nimbus',
    agentId: 'kiro',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#FF9900',
      primaryForeground: '#1A0A00',
      background: '#0A0D14',
      surface: '#131720',
      border: '#232840',
      text: '#E8EAF4',
      textMuted: '#6A7090',
      sidebar: '#070A10',
      sidebarActive: '#1C2238',
    },
    light: {
      primary: '#FF9900',
      primaryForeground: '#FFFFFF',
      background: '#FAFBFF',
      surface: '#F0F2FC',
      border: '#D8DCF0',
      text: '#0A0D1A',
      textMuted: '#5A6080',
      sidebar: '#EAECF8',
      sidebarActive: '#D8DCF0',
    },
  },
  {
    id: 'amazonq-dark',
    label: 'Amazon Q — Dark',
    agentId: 'amazonq',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#FF9900',
      primaryForeground: '#1A0800',
      background: '#0A0C10',
      surface: '#141820',
      border: '#252A3A',
      text: '#EAEBf0',
      textMuted: '#6A7090',
      sidebar: '#070910',
      sidebarActive: '#1E2338',
    },
    light: {
      primary: '#CC7700',
      primaryForeground: '#FFFFFF',
      background: '#FAFBFF',
      surface: '#F0F2FC',
      border: '#D8DCF0',
      text: '#0A0D1A',
      textMuted: '#5A6080',
      sidebar: '#EAECF8',
      sidebarActive: '#D8DCF0',
    },
  },
  {
    id: 'amazonq-light',
    label: 'Amazon Q — Light',
    agentId: 'amazonq',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E8850A',
      primaryForeground: '#1A0800',
      background: '#0E0C0A',
      surface: '#181510',
      border: '#2A2418',
      text: '#F0EAE0',
      textMuted: '#8A7A60',
      sidebar: '#0A0806',
      sidebarActive: '#251E14',
    },
    light: {
      primary: '#8B6914',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#FAF8F4',
      border: '#E8E0D0',
      text: '#1A160A',
      textMuted: '#6A6050',
      sidebar: '#F5F0E8',
      sidebarActive: '#EDE4D4',
    },
  },
  {
    id: 'warp-night',
    label: 'Warp — Night',
    agentId: 'warp',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#00D4FF',
      primaryForeground: '#001A22',
      background: '#050A10',
      surface: '#0C1420',
      border: '#162130',
      text: '#C8E8F8',
      textMuted: '#3A6880',
      sidebar: '#020610',
      sidebarActive: '#0E1C2E',
    },
    light: {
      primary: '#006E8A',
      primaryForeground: '#FFFFFF',
      background: '#F4FAFF',
      surface: '#E6F4FC',
      border: '#B8D8EC',
      text: '#061828',
      textMuted: '#3A6070',
      sidebar: '#D8EEF8',
      sidebarActive: '#C0E2F0',
    },
  },
  {
    id: 'warp-dawn',
    label: 'Warp — Dawn',
    agentId: 'warp',
    borderRadius: 'lg',
    fontFamily: 'mono',
    dark: {
      primary: '#38BDF8',
      primaryForeground: '#021018',
      background: '#070C14',
      surface: '#0F1620',
      border: '#1A2840',
      text: '#CAE8FC',
      textMuted: '#406880',
      sidebar: '#040810',
      sidebarActive: '#112030',
    },
    light: {
      primary: '#0284C7',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0F8FF',
      border: '#BAD8F0',
      text: '#051422',
      textMuted: '#305A70',
      sidebar: '#E0F0FA',
      sidebarActive: '#C6E4F5',
    },
  },
  {
    id: 'kiro-storm',
    label: 'Kiro — Storm',
    agentId: 'kiro',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#FF6600',
      primaryForeground: '#1A0500',
      background: '#0D0C0A',
      surface: '#181614',
      border: '#2E2820',
      text: '#F0EAE0',
      textMuted: '#8A7A60',
      sidebar: '#090806',
      sidebarActive: '#281F14',
    },
    light: {
      primary: '#CC5200',
      primaryForeground: '#FFFFFF',
      background: '#FFFCF8',
      surface: '#FFF5EA',
      border: '#F0DDCC',
      text: '#1A0E06',
      textMuted: '#7A5A3A',
      sidebar: '#FDEEDD',
      sidebarActive: '#FAE0C4',
    },
  },
]
