import type { ThemeConfig } from '@/shared/types/theme'

/** Presets for the additional adapter-registry agents (one default theme each). */
export const moreAgentThemes: ThemeConfig[] = [
  {
    id: 'windsurf-wave',
    label: 'Windsurf — Wave',
    agentId: 'windsurf',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#13C2C2',
      primaryForeground: '#04201F',
      background: '#0A1414',
      surface: '#10201F',
      border: '#1F3A38',
      text: '#E2F2F1',
      textMuted: '#6E908D',
      sidebar: '#06100F',
      sidebarActive: '#143230',
    },
    light: {
      primary: '#0E8F8F',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F2FAFA',
      border: '#D2E8E7',
      text: '#0E2422',
      textMuted: '#5C7D7A',
      sidebar: '#ECF7F6',
      sidebarActive: '#D9F0EF',
    },
  },
  {
    id: 'windsurf-storm',
    label: 'Windsurf — Storm',
    agentId: 'windsurf',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#00F5FF',
      primaryForeground: '#001820',
      background: '#040D12',
      surface: '#091520',
      border: '#0E2A3A',
      text: '#C8F0FF',
      textMuted: '#3D7A8A',
      sidebar: '#020A0F',
      sidebarActive: '#0A2030',
    },
    light: {
      primary: '#006F80',
      primaryForeground: '#FFFFFF',
      background: '#F0FAFF',
      surface: '#E2F5FC',
      border: '#B0DCE8',
      text: '#062030',
      textMuted: '#3A6878',
      sidebar: '#D8EFF8',
      sidebarActive: '#C0E4F2',
    },
  },
  {
    id: 'continue-loop',
    label: 'Continue — Loop',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E6E6E6',
      primaryForeground: '#121212',
      background: '#0D0D0D',
      surface: '#181818',
      border: '#2C2C2C',
      text: '#EDEDED',
      textMuted: '#8A8A8A',
      sidebar: '#070707',
      sidebarActive: '#222222',
    },
    light: {
      primary: '#1A1A1A',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F7F7F7',
      border: '#E2E2E2',
      text: '#1A1A1A',
      textMuted: '#6A6A6A',
      sidebar: '#F2F2F2',
      sidebarActive: '#E6E6E6',
    },
  },
  {
    id: 'continue-ember',
    label: 'Continue — Ember',
    agentId: 'continue',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#E8622A',
      primaryForeground: '#1A0800',
      background: '#0F0A08',
      surface: '#1A110D',
      border: '#2E1C14',
      text: '#F0E0D8',
      textMuted: '#8A5C48',
      sidebar: '#0A0604',
      sidebarActive: '#271510',
    },
    light: {
      primary: '#C0440E',
      primaryForeground: '#FFFFFF',
      background: '#FFFAF7',
      surface: '#FFF3EC',
      border: '#F0D4C4',
      text: '#1A0800',
      textMuted: '#7A4030',
      sidebar: '#FEEEE4',
      sidebarActive: '#FDE0CC',
    },
  },
  {
    id: 'aider-slate',
    label: 'Aider — Slate',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#7FB069',
      primaryForeground: '#0C1408',
      background: '#101311',
      surface: '#1A1F1B',
      border: '#2C342D',
      text: '#E4EAE2',
      textMuted: '#7E8A7C',
      sidebar: '#0B0E0C',
      sidebarActive: '#222B23',
    },
    light: {
      primary: '#4F7942',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F5F7F4',
      border: '#DDE3DA',
      text: '#1A201A',
      textMuted: '#647062',
      sidebar: '#EFF2ED',
      sidebarActive: '#E1E8DD',
    },
  },
  {
    id: 'aider-rust',
    label: 'Aider — Rust',
    agentId: 'aider',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#B8632A',
      primaryForeground: '#140800',
      background: '#0E0B08',
      surface: '#171210',
      border: '#2A1E18',
      text: '#E8DDD5',
      textMuted: '#7A5E50',
      sidebar: '#090704',
      sidebarActive: '#231812',
    },
    light: {
      primary: '#8B3C10',
      primaryForeground: '#FFFFFF',
      background: '#FDFAF7',
      surface: '#F7F0E8',
      border: '#E0CEC0',
      text: '#1A1008',
      textMuted: '#6A4E3A',
      sidebar: '#F2E8DC',
      sidebarActive: '#E8D8C8',
    },
  },
  {
    id: 'cline-night',
    label: 'Cline — Night',
    agentId: 'cline',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#1A0F2E',
      background: '#0E0D14',
      surface: '#17151F',
      border: '#2A2738',
      text: '#E8E6F0',
      textMuted: '#827E96',
      sidebar: '#09080F',
      sidebarActive: '#211D33',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F8F7FC',
      border: '#E5E1F0',
      text: '#1B1826',
      textMuted: '#6B6680',
      sidebar: '#F1EFF9',
      sidebarActive: '#E6E0F5',
    },
  },
  {
    id: 'cline-dawn',
    label: 'Cline — Dawn',
    agentId: 'cline',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#E879A8',
      primaryForeground: '#200010',
      background: '#110A14',
      surface: '#1A1020',
      border: '#2E1A38',
      text: '#F0E0F5',
      textMuted: '#8A5A90',
      sidebar: '#0C0610',
      sidebarActive: '#25122E',
    },
    light: {
      primary: '#C42A70',
      primaryForeground: '#FFFFFF',
      background: '#FFF8FC',
      surface: '#FDEEF6',
      border: '#F0CEDF',
      text: '#200010',
      textMuted: '#7A3060',
      sidebar: '#FAE4F0',
      sidebarActive: '#F5D0E5',
    },
  },
  {
    id: 'amp-forge',
    label: 'Amp — Forge',
    agentId: 'amp',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#F59E0B',
      primaryForeground: '#1C1200',
      background: '#141210',
      surface: '#1E1B16',
      border: '#332D20',
      text: '#F0EAD6',
      textMuted: '#8A7E60',
      sidebar: '#0D0B08',
      sidebarActive: '#2B2416',
    },
    light: {
      primary: '#B45309',
      primaryForeground: '#FFFFFF',
      background: '#FFFBF0',
      surface: '#FFF7E1',
      border: '#F0DFA0',
      text: '#1C1200',
      textMuted: '#7A6830',
      sidebar: '#FFF3CC',
      sidebarActive: '#FDEEA0',
    },
  },
  {
    id: 'goose-feather',
    label: 'Goose — Feather',
    agentId: 'goose',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#021A18',
      background: '#080F0F',
      surface: '#0F1A1A',
      border: '#1A2E2D',
      text: '#E2F5F4',
      textMuted: '#5E8C89',
      sidebar: '#050C0C',
      sidebarActive: '#132322',
    },
    light: {
      primary: '#0D9488',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0FAFA',
      border: '#CCEAE8',
      text: '#0A1F1E',
      textMuted: '#4A7A77',
      sidebar: '#E8F7F6',
      sidebarActive: '#D1EFED',
    },
  },
]
