import type { ThemeConfig } from '@/shared/types/theme'

export const openhandsThemes: ThemeConfig[] = [
  {
    id: 'openhands-studio',
    label: 'OpenHands — Studio',
    agentId: 'openhands',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#EF4444',
      primaryForeground: '#1A0000',
      background: '#0F1117',
      surface: '#181C26',
      border: '#252A38',
      text: '#E2E8F0',
      textMuted: '#5A6480',
      sidebar: '#090C12',
      sidebarActive: '#1E2233',
    },
    light: {
      primary: '#DC2626',
      primaryForeground: '#FFFFFF',
      background: '#F8F9FC',
      surface: '#EEF1F8',
      border: '#C8D0E4',
      text: '#0C1020',
      textMuted: '#4A5470',
      sidebar: '#E4E8F4',
      sidebarActive: '#D4DCEE',
    },
  },
  {
    id: 'openhands-dawn',
    label: 'OpenHands — Dawn',
    agentId: 'openhands',
    borderRadius: 'lg',
    fontFamily: 'sans',
    dark: {
      primary: '#F97316',
      primaryForeground: '#1A0800',
      background: '#12100E',
      surface: '#1C1916',
      border: '#2E281E',
      text: '#F0E8DC',
      textMuted: '#6A5A48',
      sidebar: '#0C0A08',
      sidebarActive: '#26201A',
    },
    light: {
      primary: '#EA580C',
      primaryForeground: '#FFFFFF',
      background: '#FFF8F2',
      surface: '#FDEEE0',
      border: '#F0C8A0',
      text: '#1A0C00',
      textMuted: '#6A4020',
      sidebar: '#F8E4CC',
      sidebarActive: '#F0D0B0',
    },
  },
  {
    id: 'openhands-carbon',
    label: 'OpenHands — Carbon',
    agentId: 'openhands',
    borderRadius: 'none',
    fontFamily: 'mono',
    dark: {
      primary: '#EF4444',
      primaryForeground: '#0A0000',
      background: '#050507',
      surface: '#0C0C10',
      border: '#1A1A20',
      text: '#C8C8D0',
      textMuted: '#3A3A48',
      sidebar: '#020204',
      sidebarActive: '#14141C',
    },
    light: {
      primary: '#B91C1C',
      primaryForeground: '#FFFFFF',
      background: '#F5F5F7',
      surface: '#E8E8EC',
      border: '#C0C0CC',
      text: '#0A0A10',
      textMuted: '#3A3A50',
      sidebar: '#DCDCE4',
      sidebarActive: '#CACAD4',
    },
  },
]
