import type { ThemeConfig } from '@/shared/types/theme'

export const plandexThemes: ThemeConfig[] = [
  {
    id: 'plandex-horizon',
    label: 'Plandex — Horizon',
    agentId: 'plandex',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#F0A500',
      primaryForeground: '#1A0E00',
      background: '#0A1014',
      surface: '#111C22',
      border: '#1E3040',
      text: '#D8EEF4',
      textMuted: '#5A8A9A',
      sidebar: '#060C10',
      sidebarActive: '#162430',
    },
    light: {
      primary: '#B87800',
      primaryForeground: '#FFFFFF',
      background: '#F4FAFE',
      surface: '#E8F5FB',
      border: '#BFD9E8',
      text: '#0A1A24',
      textMuted: '#3A6A80',
      sidebar: '#DFF0F8',
      sidebarActive: '#C8E4F0',
    },
  },
  {
    id: 'plandex-abyss',
    label: 'Plandex — Abyss',
    agentId: 'plandex',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#001814',
      background: '#060E0C',
      surface: '#0C1A18',
      border: '#163028',
      text: '#C0EAE4',
      textMuted: '#3A7A70',
      sidebar: '#030A09',
      sidebarActive: '#102420',
    },
    light: {
      primary: '#0F766E',
      primaryForeground: '#FFFFFF',
      background: '#F0FDFB',
      surface: '#CCFBF4',
      border: '#99F0E4',
      text: '#002820',
      textMuted: '#2A6860',
      sidebar: '#B0F0E8',
      sidebarActive: '#88E8DC',
    },
  },
]
