import type { ThemeConfig } from '@/shared/types/theme'

export const rooThemes: ThemeConfig[] = [
  {
    id: 'roo-circuit',
    label: 'Roo Code — Circuit',
    agentId: 'roo',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#22D3A0',
      primaryForeground: '#011A12',
      background: '#080F0D',
      surface: '#0F1A17',
      border: '#1A302A',
      text: '#DAFAF0',
      textMuted: '#4D8C75',
      sidebar: '#050C09',
      sidebarActive: '#122620',
    },
    light: {
      primary: '#0B9E72',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0FBF6',
      border: '#C2EAD9',
      text: '#0A1F18',
      textMuted: '#3D7A62',
      sidebar: '#E4F7EE',
      sidebarActive: '#C8F0DE',
    },
  },
  {
    id: 'roo-pulse',
    label: 'Roo Code — Pulse',
    agentId: 'roo',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#C4A832',
      primaryForeground: '#120E00',
      background: '#0D0F08',
      surface: '#171A0E',
      border: '#2C2E18',
      text: '#F0EDD8',
      textMuted: '#7A7440',
      sidebar: '#090B06',
      sidebarActive: '#222510',
    },
    light: {
      primary: '#8A7010',
      primaryForeground: '#FFFFFF',
      background: '#FDFCF4',
      surface: '#F8F4E2',
      border: '#E0D8A8',
      text: '#1A1800',
      textMuted: '#6A6030',
      sidebar: '#F2EDD4',
      sidebarActive: '#EAE4BC',
    },
  },
]
