import type { ThemeConfig } from '@/shared/types/theme'

export const voidThemes: ThemeConfig[] = [
  {
    id: 'void-obsidian',
    label: 'Void — Obsidian',
    agentId: 'void',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#8B5CF6',
      primaryForeground: '#0A0014',
      background: '#0C0C10',
      surface: '#14131C',
      border: '#26243A',
      text: '#E2DEFF',
      textMuted: '#6B5EA8',
      sidebar: '#08080D',
      sidebarActive: '#1E1B30',
    },
    light: {
      primary: '#6D28D9',
      primaryForeground: '#FFFFFF',
      background: '#FAF9FF',
      surface: '#F2EFFF',
      border: '#D6CCFF',
      text: '#12103A',
      textMuted: '#5B4A9A',
      sidebar: '#EDE9FF',
      sidebarActive: '#DDD5FF',
    },
  },
  {
    id: 'void-ash',
    label: 'Void — Ash',
    agentId: 'void',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#A3A3B8',
      primaryForeground: '#0A0A12',
      background: '#111114',
      surface: '#1A1A20',
      border: '#2C2C38',
      text: '#E8E8F0',
      textMuted: '#70708A',
      sidebar: '#0D0D10',
      sidebarActive: '#22222C',
    },
    light: {
      primary: '#5C5C78',
      primaryForeground: '#FFFFFF',
      background: '#FEFEFE',
      surface: '#F4F4F8',
      border: '#DDDDE8',
      text: '#16161E',
      textMuted: '#6A6A84',
      sidebar: '#EEEEF4',
      sidebarActive: '#E0E0EC',
    },
  },
  {
    id: 'void-plasma',
    label: 'Void — Plasma',
    agentId: 'void',
    borderRadius: 'lg',
    fontFamily: 'mono',
    dark: {
      primary: '#C084FC',
      primaryForeground: '#150028',
      background: '#0E0818',
      surface: '#170D26',
      border: '#2D1E50',
      text: '#F0E6FF',
      textMuted: '#8055C0',
      sidebar: '#09050F',
      sidebarActive: '#231540',
    },
    light: {
      primary: '#9333EA',
      primaryForeground: '#FFFFFF',
      background: '#FBF8FF',
      surface: '#F5EEFF',
      border: '#E2CCFF',
      text: '#1A0A30',
      textMuted: '#7040B0',
      sidebar: '#EDE0FF',
      sidebarActive: '#DFCCFF',
    },
  },
]
