import type { ThemeConfig } from '@/shared/types/theme'

export const warpThemes: ThemeConfig[] = [
  {
    id: 'warp-night',
    label: 'Warp — Night',
    agentId: 'warp',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#00D4FF',
      primaryForeground: '#001A22',
      background: '#050A10',
      surface: '#0C1420',
      border: '#162130',
      text: '#C8E8F8',
      textMuted: '#3A6880',
      sidebar: '#020610',
      sidebarActive: '#0E1C2E',
    },
    light: {
      primary: '#006E8A',
      primaryForeground: '#FFFFFF',
      background: '#F4FAFF',
      surface: '#E6F4FC',
      border: '#B8D8EC',
      text: '#061828',
      textMuted: '#3A6070',
      sidebar: '#D8EEF8',
      sidebarActive: '#C0E2F0',
    },
  },
  {
    id: 'warp-dawn',
    label: 'Warp — Dawn',
    agentId: 'warp',
    borderRadius: 'lg',
    fontFamily: 'mono',
    dark: {
      primary: '#38BDF8',
      primaryForeground: '#021018',
      background: '#070C14',
      surface: '#0F1620',
      border: '#1A2840',
      text: '#CAE8FC',
      textMuted: '#406880',
      sidebar: '#040810',
      sidebarActive: '#112030',
    },
    light: {
      primary: '#0284C7',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F0F8FF',
      border: '#BAD8F0',
      text: '#051422',
      textMuted: '#305A70',
      sidebar: '#E0F0FA',
      sidebarActive: '#C6E4F5',
    },
  },
  {
    id: 'warp-pulse',
    label: 'Warp — Pulse',
    agentId: 'warp',
    borderRadius: 'sm',
    fontFamily: 'mono',
    dark: {
      primary: '#39FF14',
      primaryForeground: '#020A00',
      background: '#060806',
      surface: '#0C100C',
      border: '#162016',
      text: '#C8F0C8',
      textMuted: '#3A6A3A',
      sidebar: '#040604',
      sidebarActive: '#102010',
    },
    light: {
      primary: '#1A8A00',
      primaryForeground: '#FFFFFF',
      background: '#F4FAF4',
      surface: '#E8F5E8',
      border: '#B8E0B8',
      text: '#071407',
      textMuted: '#386038',
      sidebar: '#DCF0DC',
      sidebarActive: '#C4E8C4',
    },
  },
]
