import type { ThemeConfig } from '@/shared/types/theme'

export const windsurfThemes: ThemeConfig[] = [
  {
    id: 'windsurf-wave',
    label: 'Windsurf — Wave',
    agentId: 'windsurf',
    borderRadius: 'md',
    fontFamily: 'sans',
    dark: {
      primary: '#13C2C2',
      primaryForeground: '#04201F',
      background: '#0A1414',
      surface: '#10201F',
      border: '#1F3A38',
      text: '#E2F2F1',
      textMuted: '#6E908D',
      sidebar: '#06100F',
      sidebarActive: '#143230',
    },
    light: {
      primary: '#0E8F8F',
      primaryForeground: '#FFFFFF',
      background: '#FFFFFF',
      surface: '#F2FAFA',
      border: '#D2E8E7',
      text: '#0E2422',
      textMuted: '#5C7D7A',
      sidebar: '#ECF7F6',
      sidebarActive: '#D9F0EF',
    },
  },
  {
    id: 'windsurf-storm',
    label: 'Windsurf — Storm',
    agentId: 'windsurf',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#00F5FF',
      primaryForeground: '#001820',
      background: '#040D12',
      surface: '#091520',
      border: '#0E2A3A',
      text: '#C8F0FF',
      textMuted: '#3D7A8A',
      sidebar: '#020A0F',
      sidebarActive: '#0A2030',
    },
    light: {
      primary: '#006F80',
      primaryForeground: '#FFFFFF',
      background: '#F0FAFF',
      surface: '#E2F5FC',
      border: '#B0DCE8',
      text: '#062030',
      textMuted: '#3A6878',
      sidebar: '#D8EFF8',
      sidebarActive: '#C0E4F2',
    },
  },
]
