import type { ThemeConfig } from '@/shared/types/theme'

export const zedThemes: ThemeConfig[] = [
  {
    id: 'zed-void',
    label: 'Zed — Void',
    agentId: 'zed',
    borderRadius: 'md',
    fontFamily: 'mono',
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#0D0010',
      background: '#0D0D12',
      surface: '#16151E',
      border: '#2A2540',
      text: '#DDD8F5',
      textMuted: '#6B5FA8',
      sidebar: '#0A090F',
      sidebarActive: '#1E1B30',
    },
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      background: '#F9F8FF',
      surface: '#F0EEFF',
      border: '#D4CCEF',
      text: '#1A1530',
      textMuted: '#5E4EA0',
      sidebar: '#EAE6FF',
      sidebarActive: '#D8D0F5',
    },
  },
  {
    id: 'zed-paper',
    label: 'Zed — Paper',
    agentId: 'zed',
    borderRadius: 'sm',
    fontFamily: 'sans',
    dark: {
      primary: '#C084FC',
      primaryForeground: '#130020',
      background: '#100E18',
      surface: '#1A1826',
      border: '#302A50',
      text: '#E8E0FF',
      textMuted: '#7060AA',
      sidebar: '#0C0A14',
      sidebarActive: '#221E38',
    },
    light: {
      primary: '#9333EA',
      primaryForeground: '#FFFFFF',
      background: '#FEFEFE',
      surface: '#F5F3FF',
      border: '#E2DAFF',
      text: '#120E28',
      textMuted: '#6B5499',
      sidebar: '#F8F5FF',
      sidebarActive: '#ECE6FF',
    },
  },
]
