/**
 * Generate and manage Claude Code's status line. Abyss writes a small,
 * self-contained CommonJS script next to the agent's `settings.json` and points
 * `statusLine.command` at it (`node "<script>"`). The script reads Claude Code's
 * session JSON from stdin and prints the composed line. The builder config is
 * embedded in the script as a comment so we can round-trip the UI state.
 * Node-only. See https://code.claude.com/docs/en/statusline
 */

import path from 'node:path'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import {
  DEFAULT_STATUSLINE,
  type StatusLineConfig,
  type StatusLineSegmentId,
} from '@/shared/types/statusline'
import { SEGMENT_DEFS } from '@/shared/statusline/segments'
import { readJsonFile, writeJsonFile } from './json-file'

const SCRIPT_NAME = 'abyss-statusline.cjs'
const CONFIG_MARKER = 'ABYSS-CONFIG'

interface SettingsWithStatusLine {
  statusLine?: { type?: string; command?: string; padding?: number }
  [key: string]: unknown
}

function settingsPath(basePath: string): string {
  return path.join(basePath, 'settings.json')
}

function scriptPath(basePath: string): string {
  return path.join(basePath, SCRIPT_NAME)
}

/** Embedded, round-trippable subset of the builder config. */
interface EmbeddedConfig {
  segments: StatusLineSegmentId[]
  separator: string
  padding: number
  dirBasename: boolean
  icons: boolean
}

function generateScript(cfg: StatusLineConfig): string {
  const segData = cfg.segments
    .map((id) => SEGMENT_DEFS.find((d) => d.id === id))
    .filter((d): d is (typeof SEGMENT_DEFS)[number] => Boolean(d))
    .map((d) => ({
      source: d.source,
      path: d.path,
      format: d.format,
      icon: d.icon,
    }))

  const embedded: EmbeddedConfig = {
    segments: cfg.segments,
    separator: cfg.separator,
    padding: cfg.padding,
    dirBasename: cfg.dirBasename,
    icons: cfg.icons,
  }

  const segJson = JSON.stringify(segData)
  const sepJson = JSON.stringify(cfg.separator)
  // Embed the round-trip config as a single-line `//` comment with minified
  // JSON: a line comment can't be closed early by a `*/` inside a user-set
  // separator the way a block comment could.
  const configLine = `// ${CONFIG_MARKER} ${JSON.stringify(embedded)} ${CONFIG_MARKER}`

  // The runtime body avoids template `${}` so it stays literal inside this
  // generator. It mirrors `renderStatusLine` in shared/statusline/segments.ts.
  return `#!/usr/bin/env node
/* eslint-disable */
// ABYSS-STATUSLINE v1 — generated by Abyss. Manual edits will be overwritten.
${configLine}
'use strict'
const { execSync } = require('node:child_process')

const SEGMENTS = ${segJson}
const SEP = ${sepJson}
const ICONS = ${cfg.icons ? 'true' : 'false'}
const DIRB = ${cfg.dirBasename ? 'true' : 'false'}

function get(o, p) {
  return p.split('.').reduce(function (a, k) {
    return a != null && typeof a === 'object' ? a[k] : undefined
  }, o)
}
function base(p) {
  var parts = String(p).split(/[\\\\/]/).filter(Boolean)
  return parts[parts.length - 1] || String(p)
}
function value(s, d) {
  if (s.source === 'git') {
    var dir = get(d, 'workspace.current_dir') || process.cwd()
    try {
      return (
        execSync('git -C "' + dir + '" rev-parse --abbrev-ref HEAD', {
          stdio: ['ignore', 'pipe', 'ignore'],
        })
          .toString()
          .trim() || null
      )
    } catch (e) {
      return null
    }
  }
  if (s.format === 'lines') {
    var a = Number(get(d, 'cost.total_lines_added') || 0)
    var r = Number(get(d, 'cost.total_lines_removed') || 0)
    return '+' + a + ' -' + r
  }
  var raw = s.path ? get(d, s.path) : undefined
  if (raw == null || raw === '') return null
  switch (s.format) {
    case 'basename':
      return DIRB ? base(raw) : String(raw)
    case 'percent':
      return Math.round(Number(raw)) + '%'
    case 'money':
      return '$' + Number(raw).toFixed(2)
    case 'shortid':
      return String(raw).slice(0, 8)
    default:
      return String(raw)
  }
}

var input = ''
process.stdin.setEncoding('utf8')
process.stdin.on('data', function (c) {
  input += c
})
process.stdin.on('end', function () {
  var data = {}
  try {
    data = JSON.parse(input)
  } catch (e) {}
  var out = []
  for (var i = 0; i < SEGMENTS.length; i++) {
    var s = SEGMENTS[i]
    var v = null
    try {
      v = value(s, data)
    } catch (e) {}
    if (v == null || v === '') continue
    out.push(ICONS && s.icon ? s.icon + ' ' + v : v)
  }
  process.stdout.write(out.join(SEP))
})
`
}

function parseEmbedded(script: string): EmbeddedConfig | null {
  const re = new RegExp(`${CONFIG_MARKER}\\s+([\\s\\S]*?)\\s+${CONFIG_MARKER}`)
  const match = re.exec(script)
  if (!match) return null
  try {
    return JSON.parse(match[1]) as EmbeddedConfig
  } catch {
    return null
  }
}

export async function readStatusLine(
  basePath: string,
): Promise<StatusLineConfig> {
  const s = await readJsonFile<SettingsWithStatusLine>(
    settingsPath(basePath),
    {},
  )
  const sl = s.statusLine
  if (!sl?.command) return { ...DEFAULT_STATUSLINE }

  const managed = sl.command.includes(SCRIPT_NAME)
  if (!managed) {
    return {
      ...DEFAULT_STATUSLINE,
      configured: true,
      managed: false,
      rawCommand: sl.command,
    }
  }

  try {
    const script = await readFile(scriptPath(basePath), 'utf8')
    const embedded = parseEmbedded(script)
    if (embedded) {
      return {
        configured: true,
        managed: true,
        segments: embedded.segments,
        separator: embedded.separator,
        padding: sl.padding ?? embedded.padding,
        dirBasename: embedded.dirBasename,
        icons: embedded.icons,
      }
    }
  } catch {
    // Script missing or unreadable — fall back to a managed default below.
  }
  return { ...DEFAULT_STATUSLINE, configured: true, managed: true }
}

export async function writeStatusLine(
  basePath: string,
  cfg: StatusLineConfig,
): Promise<{ success: boolean; path: string }> {
  await mkdir(basePath, { recursive: true })
  const script = scriptPath(basePath)
  await writeFile(script, generateScript(cfg), { mode: 0o755 })

  const p = settingsPath(basePath)
  const s = await readJsonFile<SettingsWithStatusLine>(p, {})
  s.statusLine = {
    type: 'command',
    command: `node "${script}"`,
    ...(cfg.padding > 0 ? { padding: cfg.padding } : {}),
  }
  await writeJsonFile(p, s)
  return { success: true, path: p }
}

export async function removeStatusLine(
  basePath: string,
): Promise<{ success: boolean; path: string }> {
  const p = settingsPath(basePath)
  const s = await readJsonFile<SettingsWithStatusLine>(p, {})
  delete s.statusLine
  await writeJsonFile(p, s)
  // Best-effort cleanup of the generated script; absence is fine.
  try {
    await unlink(scriptPath(basePath))
  } catch {
    // ignore
  }
  return { success: true, path: p }
}
